### ISSUE TITLE
Us Introduction Wiki V1.0

### ISSUE THREAD

**Issue by shervine** [USfoundation/foundation-web-app#40]
This would gather all the explanations of Us so far from:

- YC Application
- Website intro/wiki pages
- our thoughts

and put them in a centralized Wiki where we can share with everyone and continuously improve.

**Comment by shervine** [comment]
@grumo This is what I just left you a voice note on.

I have added this to v0.6 which I plan to release by April 28th.

You can see all future development milestones here:

https://github.com/USfoundation/us-indexer/milestones

Will ping you once I have the first version up by early next week.

**Comment by grumo** [comment]
I'm keeping an index with all main Us properties [HERE](https://docs.google.com/spreadsheets/d/1uBdA7arZMHavnajGThrmF-0kknxjasih3aMzjcZj76Y/edit?usp=sharing)

**Comment by shervine** [comment]
@grumo Awesome we can keep growing this.

**Comment by shervine** [comment]
We will be making videos to explain Us, as we better define its identity.

For the development guide, I am working on it for new developers on this issue:

https://github.com/USfoundation/foundation-web-app/issues/95
