### ISSUE TITLE
Home Page Copy Revision

### ISSUE THREAD

**Issue by shervine** [USfoundation/foundation-web-app#69]
Make it more tangible and focused on the immediate value.

**Comment by grumo** [comment]
Current version:

Intelligence to Grow. Faster.

Us is a decentralized platform to store, organize and distribute knowledge that contributes to your most important goals. We're currently gathering intelligence on growing a startup.

How Us works?


Crowdsourcing
We connect human intelligence to create AI.


Credibility Based
We score data using author credentials & qualifications.


Goal-Driven
We correlate best-practices to specific, tangible goals.


Personalized
2-Way interactions gives you data that matters.


On-Demand
Instantly access actionable insights by searching goals.


For All of Us.
We are both open-source & non-profit.

Our mission is to Extend Human Survival.

The question we're most concerned about is: 
Would we humans be growing a million years from now?

We believe leveraging our common intelligence would increase our chances.

**Comment by shervine** [comment]
@grumo I think we can benefit from the use of Emoji as a globally known icons to transfer meaning:

https://apps.timwhitlock.info/emoji/tables/unicode

**Comment by shervine** [comment]
@grumo I also think the next version of the home page should directly focus on "Hypergrowing a Startup" which is our current thesis for where we want to take Us. We can think more about this...

**Comment by shervine** [comment]
@grumo I think the next version of our home page should specifically target "Pre-Product-Market-Fit Startup CEOs", who are our initial target and it should present the core value propositions we have for that group.

If you agree, would you be able to draft the replacement content on what you believe should show on the home page? This can also be accompanied by a video later on...

**Comment by shervine** [comment]
@grumo I moved this issue to the user MVP launch milestone due May 5th.

**Comment by shervine** [comment]
Moving this to a new issue focused on a landing page for our Burning Man Bot:

https://github.com/USfoundation/foundation-web-app/issues/100
