### ISSUE TITLE
KazBot Short Intro Video for Bot Introduction

### ISSUE THREAD

**Issue by shervine** [USfoundation/foundation-web-app#77]
@grumo Lets make a short video for first time users that gives them an overview of Us.

This is part of V0.60 User MVP for our May 5th.

**Comment by shervine** [comment]
@grumo I would love to make a few short videos to introduce the Bot to our new visitors and explain to them how it works and where our knowledge comes from.

We can talk more about this during our Thursday meeting.

Would set its milestone to V0.6 due May 19th.

**Comment by shervine** [comment]
@grumo We need a short, energetic introductory video that is between 60-90 seconds that introduced KazBot to the people. Here are the things I think we need to mention in this video:

- The team behind it and our human support (Us & KazBah team)
- Our intention behind it (To give back and streamline your burning man experience)
- How it works (Asks micro questions, and gives you data based on your answers, plus you can search anything and get instant answer if exists, and human answer if not!)

You can expand/modify this list from here.

**Comment by grumo** [comment]
Script is developing [HERE](https://docs.google.com/document/d/1udpc06I0gkrWxgWIWkoJ5Uta7OTkbH02h_Phh0SjRCg/edit#)

**Comment by grumo** [comment]
Script V1 YouTube Video [HERE](https://www.youtube.com/watch?v=Jr8jwS2ZAOE).

**Comment by shervine** [comment]
@grumo Really like the simplicity of this script, as it would help us spread the message easier for now.

**Comment by grumo** [comment]
Kazbot Trailer V1 [HERE](https://www.youtube.com/watch?v=jH0LMfxLNis).

**Comment by shervine** [comment]
@grumo Closing this issue as the two videos you have are a great start.
